name: Build Kernel with KernelSU

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout kernel source
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y bc bison flex libssl-dev make libc6-dev libncurses5-dev gcc clang ccache git expect

      - name: Integrate KernelSU-Next
        run: |
          curl -LSs "https://raw.githubusercontent.com/rifsxd/KernelSU-Next/next/kernel/setup.sh" | bash -

      - name: Integrate SUSFS
        run: |
          curl -LSs "https://raw.githubusercontent.com/rifsxd/KernelSU-Next/next-susfs/kernel/setup.sh" | bash -s next-susfs

      - name: Set default LITTLE/BIG CPU MASK
        run: |
          sed -i '/^LITTLE_CPU_MASK/d' .config || true
          sed -i '/^BIG_CPU_MASK/d' .config || true
          echo 'LITTLE_CPU_MASK=0' >> .config
          echo 'BIG_CPU_MASK=0' >> .config

      - name: Configure kernel (defconfig)
        run: |
          make ARCH=arm64 defconfig

      - name: Fix kernel config (auto oldconfig)
        run: |
          sudo apt-get install -y expect
          expect <<EOF
          spawn make ARCH=arm64 oldconfig
          expect {
            -re "Bitmask of available LITTLE CPUs.*" { send "0\r"; exp_continue }
            -re "Bitmask of available BIG CPUs.*" { send "0\r"; exp_continue }
            eof
          }
          EOF

      - name: Build kernel
        run: |
          make -j$(nproc) ARCH=arm64

      - name: Upload kernel image
        uses: actions/upload-artifact@v4
        with:
          name: kernel-image
          path: |
            arch/arm64/boot/Image*
            arch/arm64/boot/dts/*.dtb 