name: Build Kernel with KernelSU

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout kernel source
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y bc bison flex libssl-dev make libc6-dev libncurses5-dev gcc clang ccache git expect gcc-aarch64-linux-gnu

      - name: Integrate KernelSU-Next
        run: |
          curl -LSs "https://raw.githubusercontent.com/rifsxd/KernelSU-Next/next/kernel/setup.sh" | bash -

      - name: Integrate SUSFS
        run: |
          curl -LSs "https://raw.githubusercontent.com/rifsxd/KernelSU-Next/next-susfs/kernel/setup.sh" | bash -s next-susfs

      - name: Set default LITTLE/BIG CPU MASK
        run: |
          sed -i '/^LITTLE_CPU_MASK/d' .config || true
          sed -i '/^BIG_CPU_MASK/d' .config || true
          echo 'LITTLE_CPU_MASK=0' >> .config
          echo 'BIG_CPU_MASK=0' >> .config

      - name: Configure kernel (defconfig)
        run: |
          make ARCH=arm64 defconfig

      - name: Patch LITTLE/BIG CPU MASK
        run: |
          sed -i '/^CONFIG_LITTLE_CPU_MASK/d' .config || true
          sed -i '/^CONFIG_BIG_CPU_MASK/d' .config || true
          echo 'CONFIG_LITTLE_CPU_MASK=0' >> .config
          echo 'CONFIG_BIG_CPU_MASK=8' >> .config

      - name: Debug .config after patch
        run: cat .config

      - name: Build kernel
        run: |
          make -j$(nproc) ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- V=1 2>&1 | tee build.log

      - name: Show build log (last 100 lines)
        if: failure()
        run: tail -n 100 build.log || true

      - name: List kernel output
        run: ls -lh arch/arm64/boot/ || true
      - name: List DTB output
        run: ls -lh arch/arm64/boot/dts/ || true
      - name: List xilinx output
        run: ls -lh arch/arm64/boot/xilinx/ || true
      - name: Find all kernel images
        run: find . -type f -name 'Image*' -o -name 'zImage*' -o -name '*.dtb' || true

      - name: Upload kernel image
        uses: actions/upload-artifact@v4
        with:
          name: kernel-image
          path: |
            arch/arm64/boot/Image*
            arch/arm64/boot/Image.gz*
            arch/arm64/boot/zImage*
            arch/arm64/boot/dts/*.dtb

      - name: Build kernel image
        run: |
          make -j$(nproc) ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- Image

      - name: List all files in arch/arm64/boot/
        run: ls -lh arch/arm64/boot/ || true 